describe('Visiting webpages', function() {
  var baseURL;
  baseURL = browser.baseUrl;
  return it('External websites should load.', function() {
    browser.get('http://juliemr.github.io/protractor-demo/');
    return expect(browser.getTitle()).toEqual('Super Calculator');
  });
});

// ---
// generated by coffee-script 1.9.2
